### ISSUE TITLE
Update READ.ME + use dylibbundler

### ISSUE THREAD

**Issue by Selur** [yuygfgg/Macos_vapoursynth_plugins#2]
How to use this repository?
I used checked out the repository to: /Users/selur/workspace/Macos_vapoursynth_plugins
I created "$HOME/Library/Application\ Support/VapourSynth/vapoursynth.conf"
```
UserPluginDir=/Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs
SystemPluginDir=/opt/homebrew/opt/vapoursynth/lib/
```
then I tried a simple:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
core = vs.core
# Source: '/Users/selur/Desktop/test.avi'
# Current color space: YUV420P8, bit depth: 8, resolution: 640x352, frame rate: 25fps, scanorder: progressive, yuv luminance scale: limited, matrix: 470bg, format: MPEG-4 Visual
# Loading /Users/selur/Desktop/test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="/Users/selur/Desktop/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)

# output
clip.set_output()
```
and got tons for errors like:
```
Failed to load /Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs/liblsmashsource.1.dylib. Error given: dlopen(/Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs/liblsmashsource.1.dylib, 0x0001): Library not loaded: /usr/local/lib/libavcodec.61.dylib
Referenced from: /Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs/liblsmashsource.1.dylib
Reason: tried: '/usr/local/lib/libavcodec.61.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libavcodec.61.dylib' (no such file), '/usr/local/lib/libavcodec.61.dylib' (no such file)
Failed to load /Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs/liblsmashsource.1.dylib. Error given: dlopen(/Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs/liblsmashsource.1.dylib, 0x0001): Library not loaded: /usr/local/lib/libavcodec.61.dylib
Referenced from: /Users/selur/workspace/Macos_vapoursynth_plugins/vapoursynth-libs/liblsmashsource.1.dylib
Reason: tried: '/usr/local/lib/libavcodec.61.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libavcodec.61.dylib' (no such file), '/usr/local/lib/libavcodec.61.dylib' (no such file)
....
Python exception: No attribute with the name lsmas exists. Did you mistype a plugin namespace or forget to install a plugin?

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluate
File "/Users/selur/Desktop/temp/tempPreviewVapoursynthFile10_54_27_098.vpy", line 8, in 
clip = core.lsmas.LWLibavSource(source="/Users/selur/Desktop/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
^^^^^^^^^^
File "src/cython/vapoursynth.pyx", line 2895, in vapoursynth._CoreProxy.__getattr__
File "src/cython/vapoursynth.pyx", line 2701, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name lsmas exists. Did you mistype a plugin namespace or forget to install a plugin?
```
Seems like (tons of) dependencies are missing.
Should one install brew and use brew.sh? (or what is the recommended way? README.md doesn't really help)
It seems like the 'local-lib'-folder contains (some of?) them, but the dylib files do not look inside the 'local-lib'-folder. :/
Suggestion: Maybe these could be added using dylibbundler?

**Comment by yuygfgg** [comment]
Please check the GitHub ci configuration.

**Comment by Selur** [comment]
brew.sh does installs automake&co which should not be needed just for the integration,...
Okay, you might want to add this to the README.
=> I'll come up with my own script then.
